#!/usr/bin/env bash
a="5"
if [ "$#" -lt "$a" ]
  then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -eq "$a" ]
    scp -i "$4" -o StrictHostKeychecking=off "$1" "$3"@"$2":  
fi
 
