#!/usr/bin/env bash
# This script transfers a file from a client to a server
a="4"
if [ "$#" -eq "$a" ]
   then
    scp -i "$4" -o StrictHostKeychecking=no "$1" "$3@$2":~/  
else
 echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
