#!/usr/bin/env bash
# This script installs and configure nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo systemctl start nginx
