#!/usr/bin/env bash
# Install nginx and insert a redirection
sudo sed -i "30i \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=54SBHobALBQ permanent;" /etc/nginx/sites-available/default
sudo service nginx start 
