#! /usr/bin/env bash
# This script configure everything
# shellcheck disable=SC2154
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "48i \\\t \tadd_header \"X-Served-By\" \"$HOSTNAME\";" /etc/nginx/sites-available/default
sudo service nginx restart
