#!/usr/bin/env bash
# This script installs and configures HAproxy as load balancer
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y 
sudo apt-get update -y
sudo apt-get install haproxy=1.8.\* -y
echo "ENABLED=1" |sudo tee -a /etc/default/haproxy
sudo service haproxy start
echo -e "frontend http\n \tbind *:80\n \tmode http\n \tdefault_backend holberton\n backend holberton\n \tmode http\n \tbalance roundrobin\n \tserver 774-web-01 35.237.52.158:80 check\n \tserver 774-web-02 34.74.28.162:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
