#!/usr/bin/env bash
# Install nginx and insert a redirection
sudo apt-get -y update
sudo apt-get -y install nginx
sudo touch /var/www/html/my_404.html
echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/html/my_404.html
sudo sed -i "55i \\\terror_page 404 \/my_404.html;\n \tlocation \/my_404.html {\n \t \t root \/var\/www\/html;\n \t \t internal;\n \t}" /etc/nginx/sites-available/default
sudo service nginx restart
