#!/usr/bin/env bash
# This script pings five times an IP
# address passed as an argument
numargs=$#
if [ "$numargs" -ne 1 ]
   then
       echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
   else
       ping -c 5 "$1"
fi
