#!/usr/bin/env bash
# Debugging
sudo service nginx start
sed -i 's/listen 8080 default_server;t/listen 80 default_server;/g' /etc/nginx/sites-enabled/default
sed -i 's/listen [::]:8080 default_server ipv6only=on;/listen [::]:80 default_server ipv6only=on;/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
