#!/usr/bin/env bash
# This script sets an infinite loop which only closes at certain signals
echo "$$" > "/var/run/holbertonscript.pid"
while :
do
 echo "To infinity and beyond"
 sleep 2
 trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit' TERM
 trap  'echo "Y U no love me?!"' INT
 trap 'rm /var/run/holbertonscript.pid; exit' QUIT
done
