#!/usr/bin/env bash
# This script prints numbers from 1 to 20 with some conditions
i="0"
c="4"
j="9"
ta="17"
while [ $i -lt 20 ]
do 
  let "i++"
  echo "$i"
  case $i in

    $c)
     echo "bad luck from China"
    ;;
   
    $j)
     echo "bad luck from Japan"
    ;;

    $ta)
      echo "bad luch from Italy"
    ;;
  esac
done
