#!/usr/bin/env bash
# This script prints the time
h="0"
while [ $h -le "12" ]
do
   echo "Hour: $h"
   m="1"     
      while [ $m -le "59" ]
        do
          echo "$m"
          let "m +=1"
        done
   ((h++))
done
