#!/usr/bin/env bash
# This script configures some IP directions

sudo cp /etc/hosts hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' hosts.new
sed -i '$a 8.8.8.8 facebook.com' hosts.new
sudo cp ./hosts.new /etc/hosts
rm hosts.new
